name: 'Nix Flake Check'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name:  Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Build default package
        run: nix flake check --all-systems