name: "Update Flake"

on:
  workflow_dispatch:
  repository_dispatch:
  # Runs at 2AM Tue
  # schedule:
  #   - cron: "0 2 * * 2"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "GH Action - Update flake.lock"
          pr-labels: |
            dependencies
            auto-merge
